services:

  db:
    image: mongo-express
    ports:
      - 27017:27017
    volumes:
      - sampleApp:/data/db

  myapp:
    build: .
    ports:
      - 8080:8080
    environment:
      DB_URL: mongodb://db/sampleApp

volumes:
  sampleApp: