services:

  mongoDB:
    image: mongo:latest
    container_name: mongoDB
    ports:
      - 27017:27017
    volumes:
      - EmployeeVol:/data/db

  employeeapp:
    build: .
    container_name: employeeApp
    ports:
      - 8080:8080
    environment:
      DB_URL: mongodb://db/EmployeeData
    links:
      - mongoDB

volumes:
  EmployeeVol: